name: Every 15-minute cron job
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Every 15-minute cron job
        run: |
          curl --request GET \
          --url 'https://bananatrack.xyz/api/update' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
